### ISSUE TITLE
Enhancement: Make Stats folder output to Stats_$Driver.Version e.g. \Stats_388.71 for further fine-tuned benchmarking

### ISSUE THREAD

**Issue by platinum4** [UselessGuru/MultiPoolMiner#14]
I'm throwing a shitload of miners at this x86/x64 and CUDA 8/9/9.1 and seeing there are decent enough differences in power consumption per-miner change that I'd like to be able to do this automatically and have the Stats folder update dynamically when new drivers come out, or if I want to DDU and backdate drivers.  I'm guessing each driver set will have its own power consumption and then at some point in the future perhaps the miner's output could display some sort of recommendation based upon a fluctuation in stats from one driver's stats folder versus another.  Like if 388.13 was 50W less aggregate on Neoscrypt then the miner could advise on the displayoutput hey you are mining this most profitably right now but if you went back to this driver version you could reduce the power draw as well

**Comment by UselessGuru** [comment]
Just having differently named stats does not really help because you would not have an overall view of all combinations.

The best option: When changing driver versions, just copy all miners to a new name with the driver version in it, This will cause all benchmarks to run again and you could see all miner/algo/driver versions it the summary.

If you are just comparing and not really mining you could also use the '$DisplayProfitOnly=$true' config option.
