### ISSUE TITLE
Announcement: End of support for original MultiPoolMiner

### ISSUE THREAD

**Issue by UselessGuru** [UselessGuru/MultiPoolMiner#23]
As a direct result of

https://github.com/MultiPoolMiner/MultiPoolMiner/issues/2462

I got removed from the original MultiPoolMiner organisation and am no longer able to comment on other people's issues with the original MultiPoolMiner.

Instead I will direct my resources to https://github.com/Minerx117/NemosMiner.

Latest up-to-date releases:
https://github.com/Minerx117/NemosMiner/releases

**Comment by mkirov0** [comment]
Sad news for the MPM project, since I loved MPM the moment I tried it 😢.
Since I very much appreciate the features you introduced, I am going to move my rigs to Nemos as soon as you implement Afterburner Profile switching per Miner/Algo combos. Although NiceNash OS is trying to catch up with you by introducing this feature now, your development has been miles ahead!

**Comment by UselessGuru** [comment]
>  I am going to move my rigs to Nemos as soon as you implement Afterburner Profile switching per Miner/Algo combos

@mkirov0
Supported in https://github.com/Minerx117/NemosMiner/tree/testing
