### ISSUE TITLE
Miner is not retried after first fail

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#37]
DSTM miner apparently sometimes fails and the following warning is show:

![image](https://user-images.githubusercontent.com/7703320/34634442-6c11b1b6-f284-11e7-96a5-fc8a73ebc8ff.png)

After this DSTM is immediately removed from the list and not tried again. Preferably it should be tried at least 3 times before being removed.

**Comment by luismcv** [comment]
Funny, because I'm having the opposite problem while benchmarking. It kept retrying ccminer-alexis:

![screen shot 2018-01-06 at 01 07 22](https://user-images.githubusercontent.com/3525353/34634652-129e4a0a-f27e-11e7-9769-534a63807726.jpg)

I had to disable x17 for ccminer-alexis so MPM could carry on benchmarking.

**Comment by hapklaar** [comment]
Haven't encountered this issue anymore, so will close and reopen if I see it again.

**Comment by hapklaar** [comment]
It's still doing this
