### ISSUE TITLE
Questionable switching going on

### ISSUE THREAD

**Issue by hapklaar** [UselessGuru/MultiPoolMiner#55]
Why is MPM switching to Ethash in example below, while Equihash was running, more profitable and having higher accuracy?

![image](https://user-images.githubusercontent.com/7703320/34795772-afef1a86-f653-11e7-8dfb-6d69e713c41f.png)

**Comment by UselessGuru** [comment]
Read here, same procedure. UG edition uses the very same logic.

**Comment by hapklaar** [comment]
read where?

**Comment by UselessGuru** [comment]
Sorry, forgot to copy the link:

https://github.com/MultiPoolMiner/MultiPoolMiner/issues/986

**Comment by hapklaar** [comment]
I don't understand this. It was mining the most profitable coin with highest accuracy, then decided to mine another algo/coin for no good reason.

**Comment by hapklaar** [comment]
Another example. Here a different, less efficient miner is started for same algo when there was no problem with the previous one. This should not be happening

![image](https://user-images.githubusercontent.com/7703320/34905640-806ba048-f85d-11e7-9a42-2ee469909ded.png)

**Comment by UselessGuru** [comment]
I can reproduce the issue. The problem lies in this line:
 `   $BestMiners = $ActiveMiners | Select-Object Type, Index -Unique | ForEach-Object {$Miner_GPU = $_; ($ActiveMiners | Where-Object {(Compare-Object $Miner_GPU.Type $_.Type | Measure-Object).Count -eq 0 -and (Compare-Object $Miner_GPU.Index $_.Index | Measure-Object).Count -eq 0} | Sort-Object -Descending {($_ | Where-Object Profit -EQ $null | Measure-Object).Count}, {($_ | Measure-Object Profit_Bias -Sum).Sum}, {($_ | Where-Object Profit -NE 0 | Measure-Object).Count}, {($_ | Measure-Object Profit -Sum).Sum}, {$_.Algorithm}, {$_.Name} | Select-Object -First 1)}`

Even though it says `{($_ | Measure-Object Profit_Bias -Sum).Sum},` powershell sorts another miner as first item.
Intrestingly enough on the first run the most profitable miner is selected (based on Profit_bias), but on subsequent runs another miner (that is NOT most profitable according by 'Profit_bias') is the top of the picks. ??? WTF???

**Comment by platinum4** [comment]
Hi.  Fix this.  This is stealing my money from me.

**Comment by UselessGuru** [comment]
> Hi. Fix this. This is stealing my money from me.

I would appreciate if you could help me find a solution.

**Comment by Coinminer24** [comment]
Could it have anything to do with the watchdog? Or does the watchdog only kick miners? Afraid I have no scripting knowledge so probably not a meaningful contribution...

**Comment by Coinminer24** [comment]
A workaround to this issue, and a more general potential tweak, is to benchmark and then have the miner exclude the non-fastest miners for each individual algo. Probably more complex than finding the bug here though...

**Comment by platinum4** [comment]
If you only leave 1 miner per algo eventually it will get penalized by watchdog strikes and get kicked out of rotation like you won't be able to mine x17 for an hour since it lost the connection on profitability port too often

**Comment by UselessGuru** [comment]
I found the reason fot this behaviour.

Whenever MPM cannot read the hash rate for a miner (often palgin because of its missing API) the resulting hash rate is 0 which will prevent MPM to update the stats timestamp -> stats get old -> profit_bias drops -> another miner gets more profitable (even though it is not).
The whole mechanism makes sense, because some miners really fall back to 0 (e.g lost connection) and will then finally get evicted.

Workaournd (for now): Edit all miner files manually and disable all slower variants of any given algorithm.

**Comment by hapklaar** [comment]
Great you found it, but why close without fix?
